---
# An example of basic hosts-file configuration where first node hosts orderer
all:
  hosts: # localhost connection parameters, used for storing configuration while transferring it between nodes
    localhost:
      ansible_connection: local
  vars:
    domain: example.com
    # Disable kafka orderer
    kafka_orderer: false
  children:
    nodes:
      hosts:
        orderer.example.com:
          node_roles: # Describes which containers will run on this node
            - root_orderer
            - orderer
            - peer
            - root_peer
          org: mainorg # Organization name
          ansible_host: 3.85.159.106 # Real ip address or domain name of the machine
          ansible_user: ubuntu # User with sudo access
          ansible_private_key_file: ~/Downloads/fs-test.pem # Private key to identify ourselves
        # Same structure for any other nodes
        one.example.com:
          node_roles:
            - peer
          org: one
          ansible_host: 3.86.31.87
          ansible_user: ubuntu
          ansible_private_key_file: ~/Downloads/fs-test.pem
        two.example.com:
          node_roles:
            - peer
          org: two
          ansible_host: 52.207.206.47
          ansible_user: ubuntu
          ansible_private_key_file: ~/Downloads/fs-test.pem
